nextgrowAi/SET_2/next_project/next_app/urls.py
from django.urls import path
from next_app import views

# app_name='gradesApp'

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),

    path('registeradmin/',views.registeradmin,name='registeradmin'),
    path('registeruser/',views.registeruser,name='registeruser'),

    path('login/',views.userLogin,name='userLogin'),
    path('dashboard',views.dashboard,name='dashboard'),

    path('add_android_app/', views.add_android_app, name='add_android_app'),
    path('app_list/', views.app_list, name='app_list'),
    path('app_list1/', views.app_list1, name='app_list1'),

    path('app_detail/<int:app_id>/', views.app_detail, name='app_detail'),
    path('add_task_screenshot/', views.add_task_screenshot, name='add_task_screenshot'),
]

nextgrowAi/SET_2/next_project/next_project/urls.py
from django.contrib import admin
from django.urls import path,include
from next_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('next_app/',include('next_app.urls')),
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('logout/',views.userLogout,name='logout'),
    path('adminDash/',views.adminDash,name='adminDash'),
    path('userDash/',views.userDash,name='userDash'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nextgrowAi/SET_2/next_project/next_app/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Admin_User(models.Model):
    admin_user=models.OneToOneField(User,on_delete=models.CASCADE )
    phone=models.IntegerField()
    is_admin_user=models.BooleanField(default=True)
    def __str__(self):
        return self.admin_user.username

class Common_User(models.Model):
    common_user=models.OneToOneField(User,on_delete=models.CASCADE)
    phone1=models.IntegerField()
    is_admin_user=models.BooleanField(default=False)

    def __str__(self):
        return self.common_user.username
    
APP_CATEGORIES = [
    ('Entertaiment', 'Entertaiment'),
    ('Entertaiment2', 'Entertaiment2'),
    # Add more categories as needed
]

SUB_CATEGORIES = [
    ('Social_Media', 'Social_Media'),
    ('Social_Media1', 'Social_Media1'),
    # Add more sub-categories as needed
]

class AndroidApp(models.Model):
    Appname = models.CharField(max_length=100)
    Applink = models.URLField()
    App_category = models.CharField(max_length=50, choices=APP_CATEGORIES, default='category1')
    Sub_category = models.CharField(max_length=50, choices=SUB_CATEGORIES, default='sub_category1')
    App_img = models.ImageField(upload_to='App_img/')
    points = models.PositiveIntegerField()

    def __str__(self):
        return self.Appname

# user_app/models.py
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    points = models.PositiveIntegerField(default=0)     
    tasks_completed = models.PositiveIntegerField(default=0)
    # Add more fields as per your requirements (e.g., profile picture, etc.)

    def __str__(self):
        return self.user.username
    

# user_app/models.py
class TaskScreenshot(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task_description = models.CharField(max_length=200)
    screenshot_img = models.ImageField(upload_to='task_screenshots/')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.task_description}"

nextgrowAi/SET_2/next_project/templates/gradesApp/add_android_app.html
<!-- templates/admin_app/add_android_app.html -->
{% extends 'gradesApp/base1.html' %}
{% block body_block %}

<style>
    /* Style for the h2 heading */
h2 {
  font-size: 24px; /* Adjust the font size as needed */
  color: #333; /* Adjust the text color as needed */
  margin-bottom: 20px; /* Add some space below the heading */
}

/* Style for the button */
button {
  padding: 10px 20px; /* Adjust the padding as needed */
  background-color: #007bff; /* Change the background color */
  color: #fff; /* Change the text color */
  border: none; /* Remove the border */
  border-radius: 5px; /* Add rounded corners */
  cursor: pointer; /* Change the cursor to indicate interactivity */
}

/* Optional: Hover effect for the button */
button:hover {
  background-color: #0056b3; /* Change the background color on hover */
}

</style>
  <h2>Add Android App</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

nextgrowAi/SET_2/next_project/templates/gradesApp/add_task.html
<!-- your_template.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Add Task Screenshot</title>
</head>
<body>
    <h1>Add Task Screenshot</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>

nextgrowAi/SET_2/next_project/templates/gradesApp/adminDash.html
{% extends 'gradesApp/base1.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Admin Dash</h2>
        <li class="nav-item active">
            
        </li>
        <hr>
    </div>
</div>


{% endblock %}

nextgrowAi/SET_2/next_project/templates/gradesApp/app_detail.html
<!-- app_detail.html -->
{% extends 'gradesApp/base2.html' %}
{% block body_block %}

<body>
    <h1>Android App Detail</h1>
    <strong>Name:</strong> {{ app.Appname }} <br>
    <strong>Link:</strong> <a href="{{ app.Applink }}" target="_blank">{{ app.Applink }}</a> <br>
    <strong>Category:</strong> {{ app.get_App_category_display }} <br>
    <strong>Sub Category:</strong> {{ app.get_Sub_category_display }} <br>
    {% if app.App_img %}
        <img src="{{ app.App_img.url }}" alt="App Image" width="100">
    {% endif %}
    <strong>Points:</strong> {{ app.points }} <br>

 
</body>
{% endblock %}

nextgrowAi/SET_2/next_project/templates/gradesApp/app_list.html
<!-- templates/user_app/app_list.html -->
{% extends 'gradesApp/base1.html' %}
{% block body_block %}
  <h2>Android Apps and Points</h2>
  <ul>
    {% for app in apps %}
            <li>
                <strong>Name:</strong> {{ app.Appname }} <br>
                <!-- <strong>Link:</strong> <a href="{{ app.Applink }}" target="_blank">{{ app.Applink }}</a> <br>
                <strong>Category:</strong> {{ app.get_App_category_display }} <br>
                <strong>Sub Category:</strong> {{ app.get_Sub_category_display }} <br> -->
                {% if app.App_img %}
                    <img src="{{ app.App_img.url }}" alt="App Image" width="100">
                {% endif %}
                <strong>Points:</strong> {{ app.points }} <br>
                <a href="{% url 'app_detail' app_id=app.id %}"><button>View Details</button></a>
            </li>
            </li>
            <br>
        {% endfor %}
  </ul>
{% endblock %}

nextgrowAi/SET_2/next_project/templates/gradesApp/app_list1.html
<!-- templates/user_app/app_list.html -->
{% extends 'gradesApp/base2.html' %}
{% block body_block %}
  <h2>Android Apps and Points</h2>
  <ul>
    {% for app in apps %}
            <li>
                <strong>Name:</strong> {{ app.Appname }} <br>
                <!-- <strong>Link:</strong> <a href="{{ app.Applink }}" target="_blank">{{ app.Applink }}</a> <br> -->
                <!-- <strong>Category:</strong> {{ app.get_App_category_display }} <br>
                <strong>Sub Category:</strong> {{ app.get_Sub_category_display }} <br> -->
                {% if app.App_img %}
                    <img src="{{ app.App_img.url }}" alt="App Image" width="100">
                {% endif %}
                <strong>Points:</strong> {{ app.points }} <br>
                <a href="{% url 'app_detail' app_id=app.id %}"><button>View Details</button></a>
            </li>
            </li>
            <br>
        {% endfor %}
  </ul>
{% endblock %}

nextgrowAi/SET_2/next_project/templates/gradesApp/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>myGrades</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">Home</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation"></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <!-- <a class="nav-link" href="{% url "admin:index" %}">Admin</a> -->
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'register' %}" role="button">Register</a>

                </li>
                {% if user.is_authenticated %}
                    <!-- <li class="nav-item active">
                        <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>

                    </li> -->
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        
                        <a class="nav-link" href="{% url 'userLogin' %}">Login</a>

                    </li>
                {% endif %}
               
            </ul>
            
        </div>
    </nav>


<style>
body {
  margin: 0;
  font-family: "Lato", sans-serif;
}

.sidebar {
  margin: 0;
  padding: 0;
  width: 200px;
  background-color: #f1f1f1;
  position: fixed;
  height: 100%;
  overflow: auto;
}

.sidebar a {
  display: block;
  color: black;
  padding: 16px;
  text-decoration: none;
}
 
.sidebar a.active {
  background-color: #04AA6D;
  color: white;
}

.sidebar a:hover:not(.active) {
  background-color: #555;
  color: white;
}

div.content {
  margin-left: 200px;
  padding: 1px 16px;
  height: 1000px;
}

@media screen and (max-width: 700px) {
  .sidebar {
    width: 100%;
    height: auto;
    position: relative;
  }
  .sidebar a {float: left;}
  div.content {margin-left: 0;}
}

@media screen and (max-width: 400px) {
  .sidebar a {
    text-align: center;
    float: none;
  }
}
</style>
</head>
<body>

<div class="sidebar">

  <a class="nav-link" href="{% url 'add_android_app' %}">Add Android App</a>
  <a class="nav-link" href="{% url 'app_list' %}">List App</a>

  <!-- <a href="#news">News</a>
  <a href="#contact">Contact</a>
  <a href="#about">About</a> -->
</div>

<div class="container">
    {% block body_block %}
    {% endblock %}
</div>

</body>
</html>

nextgrowAi/SET_2/next_project/templates/gradesApp/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>myGrades</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">Home</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation"></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <!-- <a class="nav-link" href="{% url "admin:index" %}">Admin</a> -->
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'register' %}" role="button">Register</a>

                </li>
                {% if user.is_authenticated %}
                  
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        
                        <a class="nav-link" href="{% url 'userLogin' %}">Login</a>

                    </li>
                {% endif %}
               
            </ul>
            
        </div>
    </nav>


<style>
body {
  margin: 0;
  font-family: "Lato", sans-serif;
}

.sidebar {
  margin: 0;
  padding: 0;
  width: 200px;
  background-color: #f1f1f1;
  position: fixed;
  height: 100%;
  overflow: auto;
}

.sidebar a {
  display: block;
  color: black;
  padding: 16px;
  text-decoration: none;
}
 
.sidebar a.active {
  background-color: #04AA6D;
  color: white;
}

.sidebar a:hover:not(.active) {
  background-color: #555;
  color: white;
}

div.content {
  margin-left: 200px;
  padding: 1px 16px;
  height: 1000px;
}

@media screen and (max-width: 700px) {
  .sidebar {
    width: 100%;
    height: auto;
    position: relative;
  }
  .sidebar a {float: left;}
  div.content {margin-left: 0;}
}

@media screen and (max-width: 400px) {
  .sidebar a {
    text-align: center;
    float: none;
  }
}
</style>
</head>
<body>

<div class="sidebar">

  <a class="nav-link" href="{% url 'app_list1' %}">List App</a>
  <a class="nav-link" href="{% url 'app_list1' %}">Profile</a>
  <a class="nav-link" href="{% url 'app_list1' %}">Points</a>
  <a class="nav-link" href="{% url 'app_list1' %}">Task</a>


  

</div>

<div class="container">
    {% block body_block %}
    {% endblock %}
</div>

</body>
</html>

nextgrowAi/SET_2/next_project/templates/gradesApp/dashboard.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}
{% endblock %}

nextgrowAi/SET_2/next_project/templates/gradesApp/index.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}


<div class="jumbotron">

    <h1 class="display-3">My APP</h1>
    <hr class="my-2">
    <!-- <p>View your marks and get notes directly from teachers</p> -->
</div>

{% endblock %}

nextgrowAi/SET_2/next_project/templates/gradesApp/login.html
{% extends "gradesApp/base.html" %}
{% block body_block %}

<div class="jumbotron">
    {% if invalidlogin %}
        <h3>Please enter correct login details!</h3>
    {% endif %}
    <form action="{% url 'userLogin' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" placeholder="Enter Username">
        <label for="password">Password: </label>
        <input type="password" name="password" placeholder="Enter Password">
        <input type="Submit" value="Login">
    </form>
</div>

{% endblock %}

nextgrowAi/SET_2/next_project/templates/gradesApp/register.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">Register Here!</h1>
    <hr class="my-2">
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="{% url 'registeradmin' %}" role="button">I'm a Admin</a>
        <a class="btn btn-primary btn-lg" href="{% url 'registeruser' %}" role="button">I'm a User</a>

  </p>
</div>
{% endblock %}

nextgrowAi/SET_2/next_project/templates/gradesApp/registeradmin.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<div class="jumbotron">
   {% if registered %}
        <h1>Thanks for registering, Please Log in!</h1>
    {% else %}
        <h1>Registration for Students:</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ var_adminForm.as_p }}
            {{ var_adminAddForm.as_p }}
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
</div>


{% endblock %}

nextgrowAi/SET_2/next_project/templates/gradesApp/registeruser.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}
<div class="jumbotron">
   {% if registered %}
        <h1>Thanks for registering, Please Log in!</h1>
    {% else %}
        <h1>Registration for Teachers:</h1>
        <form action="" method="POST">
            {% csrf_token %}
            {{ var_userForm.as_p }}
            {{ var_userAddForm.as_p }}
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    {% endif %}
</div>
{% endblock %}